#!/usr/bin/env python3
"""R17 Pipeline - A800 full exploration w/ fair-esm ESMFold"""
import os, sys, json, time, glob, subprocess, copy
import numpy as np
import torch
import torch.nn.functional as F
import warnings; warnings.filterwarnings("ignore")
import esm

WORK = "/root/autodl-tmp/r17"
MPNN_DIR = "/root/autodl-tmp/ProteinMPNN"
RECYCLES = 12
os.makedirs(WORK, exist_ok=True)
for d in ["pdbs","mpnn_out","results"]:
    os.makedirs(os.path.join(WORK,d), exist_ok=True)

def load_esmfold():
    print("Loading esmfold_v1...", flush=True)
    m = esm.pretrained.esmfold_v1()
    m = m.eval().cuda()
    m.set_chunk_size(128)
    print("Loaded.", flush=True)
    return m

def predict(seq, model, recycles=RECYCLES):
    with torch.no_grad():
        out = model.infer(seq, num_recycles=recycles)
    ptm = float(out["ptm"].cpu().item())
    logits = out["plddt"]
    probs = F.softmax(logits, dim=-1)
    c = torch.linspace(0.5/37, 1-0.5/37, 37, device=logits.device)
    plddt_01 = (probs * c.unsqueeze(0)).sum(-1)
    plddt_100 = (plddt_01 * 100).cpu().numpy()
    gp = float(plddt_100.mean())
    cp = float(plddt_100[57:72].mean())
    score = 0.40*ptm + 0.30*gp/100 + 0.30*cp/100
    return {"ptm":round(ptm,4),"plddt":round(gp,1),"chromo":round(cp,1),
            "score":round(score,4),"passes":ptm>0.6 and gp>60 and cp>55}

R15 = [
    ("R14_A_T02_037","MTIPGETLLAGVVPVRVNLDGDVNGKKFKVVGEGEGDATKGELRLTFEVTEGELPLDPLLLSYILTYPLSIFRKMPKDNPLRPFYLACLPEGYVIERTLDFKGEGTLNVTSETYFDGDTLVSNITLKGTGFKEGGKLLTKKVKEIRLVGDLTITPDEEKKGVKLTYTLELTFEDGSTSTADVKELIYPKGKGPETLPEPQTLTVDLTLTAVPEVEGDRFRFEHRDPPGVEPPPLSELSK"),
    ("R14_D_T02_033","MTIPGEELLSGVVPVKVNLDGDVNGQKFKVKGEGTGDATTGKLSLEFEVTEGTLPLDPLLLSYILTYPLSIFRKMPEDDPLRPFLLACLPEGYVREITLDFEGEGTLKVKSETHFEGDTLVSNITLKGTDFKEGGKLLTKKIKSIRLVGKRTITPDEERHGVNLTYTLELTWEDGSTSTAKVKELIYPIGEGPEELPEPQEITIDEVFKAKPEVNGNKFKYEYQDEPGVTPPPLSELSK"),
    ("R14_A_T01_013","MTIPGETLLSGKVPVKVNLDGDVNGEKFKVEGEGTGDATKGELKLEFKVTEGELPLDWLLLSYILTYPLSIFKKMPADHPLKPFYLCCLPEGYIIERTLDFEGEGTLKVTSKTYFDGDTLVSEITLKGTDFKEGGKLLTKEIKEIVEEGELTITPDEEKHGVKRTYTLKLTFKDGSTLTAKVDELIYPNGKGPEKLPEAQKWTINVVYKAKPKVEGDKAKVEWKDPEGVTPPPLSELSK"),
    ("R14_A_T01_020","MTIPGDTLLAGVVPVKVKLDGDVNGEKFKVEGEGEGDATTGRLKLKFEVTEGELPLDPLLLTYILTYPLRIFRKMPADDPLKPFLKACLPEGYVVERTLDFEGEGTLKVKSKTYFDGDTLVSEIELKGTDFKEGGLLLTKKVKEIRVTGELTISPDEEKHGVNLTYTLVLTFEDGSTATAKVKELIYPIGKGPETLPAPQTLNVDFVFEAKPKVEGNKFEFEWEDPPGVEPPPLSELSK"),
    ("R14_D_T02_039","MTIPGETLLNGVVPVKVNLDGDVNGEKFKVTGEGEGDATKGELKLDFEVTEGKLPLDPLLLSFILTYPLRIFRKMPADDPLKPFYLACLPEGYVVETTLDFENEGTLKVTSKTYFEGDTLVSDITLKGTDFKKGGKLLTKKVKEIRLTGDLTVTPDEAKKGVKLTYTLVLTFEDGSTSTAKVEQLIYPNGKGPETLPAAQTLTIDWVFTAKPKVEGNKFHYEYKDPEGVEPPPLSELSK"),
    ("R14_A_T01_023","MTIPGETLLSGVVPVKVNLDGDVNGNKFKVKGEGEGDATKGYLKLKFEVTEGELPLDPLLLTFILTYPLSIFRKMPADHPLRPFLLACLPEGYVVERTFDFEGEGTLKVRSDTYFDGDTLVSDITLKGTDFKEGGKLLTKKVESIKLKGELTITPDEAKHGVKLTYTLELTFTDGSTSTAKVEELIYPIGKGPATLPAAQTWTIDFTFTSKPKVEGNKFEYEYQDTPGVEPPPLSELSK"),
]

SF = "MSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGDATNGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFSRYPDHMKRHDFFKSAMPEGYVQERTISFKDDGTYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNFNSHNVYITADKQKNGIKANFKIRHNVEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSVLSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"
AV = "MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"

NEW = [
    ("av_sf_hybrid","MSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTISFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNFNSHNVYITADKQKNGIKANFKIRHNVEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSVLSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"),
    ("sf_S30R","MSKGEELFTGVVPILVELDGDVNGHKFRVRGEGEGDATNGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFSRYPDHMKRHDFFKSAMPEGYVQERTISFKDDGTYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNFNSHNVYITADKQKNGIKANFKIRHNVEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSVLSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"),
    ("sf_Cfix","MSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGDATNGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFSRYPDHMKRHDFFKSAMPEGYVQERTISFKDDGTYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNFNSHNVYITADKQKNGIKANFKIRHNVEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSVLSKDPNEKRDHMVLLEFVTAAGIDYGMDELYK"),
    ("sf_diso","MSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGDATNGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFSRYPDHMKRHDFFKSAMPEGYVQERTISFKDDGTYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNFNSHNVYITADKQKNGIKANFKIRHNVEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSVLSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"),
]

if __name__ == "__main__":
    t0 = time.time()
    print(f"R17 Start: {time.strftime('%Y-%m-%d %H:%M:%S')}", flush=True)
    model = load_esmfold()
    all_results = []

    print("\n=== R15 Top 6 Re-evaluation ===", flush=True)
    for name, seq in R15:
        m = predict(seq, model)
        m["name"] = name; m["seq"] = seq
        all_results.append(m)
        print(f"  {name}: pTM={m['ptm']:.4f} pLDDT={m['plddt']:.1f} chromo={m['chromo']:.1f} score={m['score']:.4f} pass={m['passes']}", flush=True)

    print("\n=== New Directions ===", flush=True)
    for name, seq in NEW:
        m = predict(seq, model)
        m["name"] = name; m["seq"] = seq
        all_results.append(m)
        print(f"  {name}: pTM={m['ptm']:.4f} pLDDT={m['plddt']:.1f} chromo={m['chromo']:.1f} score={m['score']:.4f} pass={m['passes']}", flush=True)

    all_results.sort(key=lambda x: x["score"], reverse=True)
    with open(os.path.join(WORK,"results","all.json"),"w") as f:
        json.dump(all_results, f, indent=2)

    print(f"\n=== FINAL Top 6 ===", flush=True)
    top6 = all_results[:6]
    import csv
    csv_path = os.path.join(WORK,"submission_r17.csv")
    with open(csv_path,"w",newline="") as f:
        w = csv.writer(f); w.writerow(["Team_Name","Seq_ID","Sequence"])
        for i,c in enumerate(top6):
            w.writerow(["SnowFold",i+1,c["seq"]])
            print(f"  {i+1}. {c['name'][:28]:<30s} pLDDT={c['plddt']:>5.1f} chromo={c['chromo']:>5.1f} pTM={c['ptm']:>.4f} score={c['score']:>.4f}", flush=True)

    json.dump(top6, open(os.path.join(WORK,"final_6_r17.json"),"w"), indent=2)
    print(f"\nDone: {time.strftime('%Y-%m-%d %H:%M:%S')} ({(time.time()-t0)/60:.1f} min)", flush=True)
